// controllers/reportController.js (Updated - Removed Status # and Status columns)

const PreAssessment = require('../models/PreAssessment');
const Project = require('../models/Project');
const Client = require('../models/Clients');
const SolarInvoice = require('../models/SolarInvoice');
const User = require('../models/Users');        // ✅ Add this
const Address = require('../models/Address');    // ✅ Add this

// Company Information
const COMPANY_INFO = {
  name: 'Salfer Engineering',
  address: 'San Nicolas St. Bunsuran 3rd, Pandi, Bulacan',
  tagline: 'Solar Technology Enterprise'
};

const REPORT_THEME = {
  navy: '#123047', blue: '#1B6CA8', lightBlue: '#EAF4FB', border: '#C8D6E0', muted: '#5E6B75'
};

// Check if optional packages are installed
let PDFDocument, ExcelJS;
try {
  PDFDocument = require('pdfkit');
} catch (err) {
  console.warn('⚠️ pdfkit not installed. PDF export will be disabled.');
}

try {
  ExcelJS = require('exceljs');
} catch (err) {
  console.warn('⚠️ exceljs not installed. Excel export will be disabled.');
}
const getExcelColumnName = (number) => {
  let column = "";

  while (number > 0) {
    const remainder = (number - 1) % 26;
    column = String.fromCharCode(65 + remainder) + column;
    number = Math.floor((number - 1) / 26);
  }

  return column;
};
// Helper function to add company header to PDF
const addCompanyHeaderToPDF = (doc) => {
  // Company Name
  const { left, right } = doc.page.margins;
  const width = doc.page.width - left - right;
  doc.save();
  doc.fillColor(REPORT_THEME.navy).font('Helvetica-Bold').fontSize(17)
    .text(COMPANY_INFO.name, left, 27, { width, align: 'center', lineBreak: false });
  doc.font('Helvetica').fontSize(8.5).fillColor(REPORT_THEME.muted)
    .text(COMPANY_INFO.address, left, 50, { width, align: 'center', lineBreak: false });
  doc.font('Helvetica-Oblique').fontSize(8).fillColor(REPORT_THEME.blue)
    .text(COMPANY_INFO.tagline, left, 64, { width, align: 'center', lineBreak: false });
  doc.strokeColor(REPORT_THEME.blue).lineWidth(2).moveTo(left, 83).lineTo(left + width, 83).stroke();
  doc.restore();
  doc.y = 105;
};

const addPdfFooter = (doc) => {
  const y = doc.page.height - 70;
  doc.save();
  doc.strokeColor(REPORT_THEME.border).lineWidth(0.5)
    .moveTo(50, y - 8).lineTo(doc.page.width - 50, y - 8).stroke();
  doc.fillColor(REPORT_THEME.muted).font('Helvetica').fontSize(7)
    .text(`Generated by ${COMPANY_INFO.name}`, 50, y, { width: doc.page.width - 100, align: 'center', lineBreak: false });
  doc.restore();
};

const drawPdfTable = (doc, headers, rows, columnWidths) => {
  const left = 50;
  const width = doc.page.width - 100;
  const rowHeight = 23;
  const drawHeader = (y) => {
    let x = left;
    doc.save().fillColor(REPORT_THEME.blue).rect(left, y, width, rowHeight).fill();
    doc.fillColor('#FFFFFF').font('Helvetica-Bold').fontSize(7.5);
    headers.forEach((header, index) => {
      doc.text(header, x + 5, y + 7, { width: columnWidths[index] - 10, lineBreak: false });
      x += columnWidths[index];
    });
    doc.restore();
  };
  let y = doc.y;
  drawHeader(y);
  y += rowHeight;
  rows.forEach((row, rowIndex) => {
    if (y + rowHeight > doc.page.height - 58) {
      addPdfFooter(doc);
      doc.addPage();
      addCompanyHeaderToPDF(doc);
      y = doc.y;
      drawHeader(y);
      y += rowHeight;
    }
    let x = left;
    doc.save();
    doc.fillColor(rowIndex % 2 ? '#FFFFFF' : REPORT_THEME.lightBlue).rect(left, y, width, rowHeight).fill();
    doc.strokeColor(REPORT_THEME.border).lineWidth(0.35).rect(left, y, width, rowHeight).stroke();
    doc.fillColor('#1F2D38').font('Helvetica').fontSize(7.3);
    row.forEach((value, index) => {
      doc.text(String(value || '—'), x + 5, y + 7, { width: columnWidths[index] - 10, lineBreak: false, ellipsis: true });
      x += columnWidths[index];
    });
    doc.restore();
    y += rowHeight;
  });
  doc.y = y;
};

const addCompanyHeaderToWorksheet = (
  worksheet,
  title,
  sectionTitle,
  recordCount
) => {

  const lastColumn = getExcelColumnName(worksheet.columns.length);

  for (let col = 1; col <= worksheet.columns.length; col++) {
    worksheet.getCell(4, col).border = {
      bottom: {
        style: "medium",
        color: { argb: "FF1B6CA8" }
      }
    };
  }

  worksheet.mergeCells(`A1:${lastColumn}1`);
  worksheet.mergeCells(`A2:${lastColumn}2`);
  worksheet.mergeCells(`A3:${lastColumn}3`);
  worksheet.mergeCells(`A5:${lastColumn}5`);
  worksheet.mergeCells(`A6:${lastColumn}6`);
  worksheet.mergeCells(`A8:${lastColumn}8`);

  worksheet.getCell("A1").value = COMPANY_INFO.name;
  worksheet.getCell("A1").font = {
    bold: true,
    size: 20,
    color: { argb: "FF123047" }
  };
  worksheet.getCell("A1").alignment = {
  horizontal: "center",
  vertical: "middle"
};

  worksheet.getCell("A2").value = COMPANY_INFO.address;
  worksheet.getCell("A2").font = {
    size: 10,
    color: { argb: "FF666666" }
  };
  worksheet.getCell("A2").alignment = {
    horizontal: "center",
    vertical: "middle"
  };

  worksheet.getCell("A3").value = COMPANY_INFO.tagline;
  worksheet.getCell("A3").font = {
    italic: true,
    size: 10,
    color: { argb: "FF1B6CA8" }
  };
  worksheet.getCell("A3").alignment = {
    horizontal: "center",
    vertical: "middle"
  };

 

  worksheet.getCell("A5").value = title;
  worksheet.getCell("A5").font = {
    bold: true,
    size: 18,
    color: { argb: "FF123047" }
  };
  worksheet.getCell("A5").alignment = {
    horizontal: "center",
    vertical: "middle"
  };

  worksheet.getCell("A6").value =
    `Generated ${new Date().toLocaleString()} • ${recordCount} record(s)`;

  worksheet.getCell("A6").font = {
    size: 10,
    color: { argb: "FF666666" }
  };

  worksheet.getCell("A6").alignment = {
    horizontal: "center",
    vertical: "middle"
  };

  worksheet.getCell("A8").value = sectionTitle;

  worksheet.getCell("A8").font = {
    bold: true,
    size: 13,
    color: { argb: "FF123047" }
  };

  worksheet.getRow(1).height = 26;
  worksheet.getRow(2).height = 18;
  worksheet.getRow(3).height = 18;
  worksheet.getRow(5).height = 30;
  worksheet.getRow(8).height = 20;

  return 9;
};

const styleWorksheetTable = (worksheet, headerRow) => {

  const header = worksheet.getRow(headerRow);

  header.height = 26;

  header.eachCell(cell => {

    cell.font = {
      bold: true,
      color: { argb: "FFFFFFFF" }
    };

    cell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF1B6CA8" }
    };

    cell.alignment = {
      horizontal: "center",
      vertical: "middle"
    };

    cell.border = {
      top: { style: "thin", color: { argb: "FFC8D6E0" } },
      left: { style: "thin", color: { argb: "FFC8D6E0" } },
      bottom: { style: "thin", color: { argb: "FFC8D6E0" } },
      right: { style: "thin", color: { argb: "FFC8D6E0" } }
    };

  });

  worksheet.eachRow((row, rowNumber) => {

    if (rowNumber <= headerRow) return;

    row.height = 22;

    row.eachCell(cell => {

      cell.alignment = {
        vertical: "middle"
      };

      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: {
          argb: rowNumber % 2
            ? "FFFFFFFF"
            : "FFEAF4FB"
        }
      };

      cell.border = {
        top: { style: "thin", color: { argb: "FFC8D6E0" } },
        left: { style: "thin", color: { argb: "FFC8D6E0" } },
        bottom: { style: "thin", color: { argb: "FFC8D6E0" } },
        right: { style: "thin", color: { argb: "FFC8D6E0" } }
      };

    });

  });

  worksheet.columns.forEach(col => {

    let max = 15;

    col.eachCell({ includeEmpty: true }, cell => {

      max = Math.max(
        max,
        String(cell.value ?? "").length + 3
      );

    });

    col.width = Math.min(max, 35);

  });

  worksheet.views = [
    {
      state: "frozen",
      ySplit: headerRow
    }
  ];

};

const buildExcelReport = ({
  workbook,
  sheetName,
  reportTitle,
  sectionTitle,
  headers,
  rows
}) => {

  const worksheet = workbook.addWorksheet(sheetName);

  worksheet.columns = headers.map(() => ({
    width: 20
  }));

  const startRow = addCompanyHeaderToWorksheet(
    worksheet,
    reportTitle,
    sectionTitle,
    rows.length
  );

  const header = worksheet.addRow(headers);

  rows.forEach(row => worksheet.addRow(row));

  styleWorksheetTable(
    worksheet,
    header.number
  );

  return worksheet;

};
// Helper function to convert assessment status string to number
const getStatusNumber = (statusString) => {
  const statusMap = {
    'pending_review': 1,
    'pending_payment': 2,
    'scheduled': 3,
    'site_visit_ongoing': 4,
    'device_deployed': 5,
    'data_collecting': 6,
    'data_analyzing': 7,
    'report_draft': 8,
    'quotation_generated': 9,
    'quotation_accepted': 10,
    'completed': 11,
    'cancelled': 12
  };
  return statusMap[statusString] || null;
};

// Assessment Status display mapping
const ASSESSMENT_STATUS_DISPLAY = {
  1: 'Pending Review',
  2: 'Pending Payment',
  3: 'Scheduled',
  4: 'Site Visit Ongoing',
  5: 'Device Deployed',
  6: 'Data Collecting',
  7: 'Data Analyzing',
  8: 'Report Draft',
  9: 'Quotation Generated',
  10: 'Quotation Accepted',
  11: 'Completed',
  12: 'Cancelled'
};

// Assessment Results Summary Ranges
const ASSESSMENT_RESULTS_SUMMARY = {
  IRRADIANCE: {
    POOR: { min: 0, max: 300, label: 'Poor' },
    MODERATE: { min: 301, max: 500, label: 'Moderate' },
    GOOD: { min: 501, max: 700, label: 'Good' },
    EXCELLENT: { min: 701, max: 1000, label: 'Excellent' }
  },
  TEMPERATURE: {
    OPTIMAL: { min: 15, max: 25, label: 'Optimal' },
    ACCEPTABLE: { min: 26, max: 35, label: 'Acceptable' },
    HIGH: { min: 36, max: 45, label: 'High - Efficiency Reduced' },
    CRITICAL: { min: 46, max: 60, label: 'Critical - Significant Loss' }
  },
  HUMIDITY: {
    LOW: { min: 0, max: 30, label: 'Low' },
    MODERATE: { min: 31, max: 60, label: 'Moderate' },
    HIGH: { min: 61, max: 80, label: 'High' },
    VERY_HIGH: { min: 81, max: 100, label: 'Very High - Condensation Risk' }
  },
  SHADING_IMPACT: {
    NEGLIGIBLE: { min: 0, max: 10, label: 'Negligible Impact' },
    LOW: { min: 11, max: 20, label: 'Low Impact' },
    MODERATE: { min: 21, max: 35, label: 'Moderate Impact' },
    SEVERE: { min: 36, max: 100, label: 'Severe Impact - Not Recommended' }
  },
  SITE_SUITABILITY: {
    POOR: { min: 0, max: 39, label: 'Poor - Not Recommended' },
    FAIR: { min: 40, max: 59, label: 'Fair - Consider with Caution' },
    GOOD: { min: 60, max: 79, label: 'Good - Recommended' },
    EXCELLENT: { min: 80, max: 100, label: 'Excellent - Highly Recommended' }
  }
};

// Helper function to get rating based on value
const getRating = (value, ranges) => {
  if (!value && value !== 0) return null;
  for (const [key, range] of Object.entries(ranges)) {
    if (value >= range.min && value <= range.max) {
      return { key, ...range };
    }
  }
  return null;
};

// Calculate suitability score based on peak sun hours and shading
const calculateSuitabilityScore = (peakSunHours, shadingPercentage, temperatureDerating) => {
  if (peakSunHours === null || peakSunHours === undefined || shadingPercentage === null || shadingPercentage === undefined) {
    return null;
  }

  let score = 100;

  // Peak Sun Hours scoring (max 40 points)
  if (peakSunHours >= 5.5) score -= 0;
  else if (peakSunHours >= 5) score -= 5;
  else if (peakSunHours >= 4.5) score -= 10;
  else if (peakSunHours >= 4) score -= 20;
  else if (peakSunHours >= 3.5) score -= 30;
  else if (peakSunHours >= 3) score -= 40;
  else score -= 50;

  // Shading Percentage scoring (max 30 points)
  if (shadingPercentage <= 5) score -= 0;
  else if (shadingPercentage <= 10) score -= 10;
  else if (shadingPercentage <= 15) score -= 20;
  else if (shadingPercentage <= 20) score -= 25;
  else score -= 30;

  // Temperature Derating scoring (max 30 points)
  const deratingAbs = Math.abs(temperatureDerating || 0);
  if (deratingAbs <= 3) score -= 0;
  else if (deratingAbs <= 5) score -= 10;
  else if (deratingAbs <= 8) score -= 20;
  else score -= 30;

  return Math.max(0, Math.min(100, Math.round(score)));
};

// Get recommendation based on score
const getRecommendation = (score) => {
  if (score === null) return 'Pending Assessment';
  if (score >= 70) return 'Suitable for Solar';
  if (score >= 50) return 'Conditional Approval';
  return 'Not Recommended';
};

// Format currency
const formatCurrency = (amount) => {
  return new Intl.NumberFormat('en-PH', {
    style: 'currency',
    currency: 'PHP',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0
  }).format(amount || 0);
};

// Helper function to get site assessment data - ONLY 5 columns
const getSiteAssessmentData = async (queryParams) => {
  const { startDate, endDate, assessmentId } = queryParams;

  let query = {};
  if (assessmentId && assessmentId.match(/^[0-9a-fA-F]{24}$/)) {
    query._id = assessmentId;
  }

  if (startDate && endDate) {
    const start = new Date(startDate);
    const end = new Date(endDate);
    if (!isNaN(start.getTime()) && !isNaN(end.getTime())) {
      query.createdAt = { $gte: start, $lte: end };
    }
  }

  const allAssessments = await PreAssessment.find(query)
    .populate('clientId', 'contactFirstName contactLastName contactNumber client_type')
    .sort({ createdAt: -1 });

  const processedAssessments = allAssessments.map(a => {
    const statusNum = getStatusNumber(a.assessmentStatus);
    const statusDisplay = ASSESSMENT_STATUS_DISPLAY[statusNum] || a.assessmentStatus;

    return {
      bookingReference: a.bookingReference || 'N/A',
      clientName: `${a.clientId?.contactFirstName || ''} ${a.clientId?.contactLastName || ''}`.trim() || 'N/A',
      clientContact: a.clientId?.contactNumber || 'N/A',
      propertyType: a.propertyType || 'N/A',
      statusDisplay: statusDisplay
    };
  });

  return {
    title: 'Site Assessment Report',
    generatedAt: new Date(),
    dateRange: { startDate, endDate },
    companyInfo: COMPANY_INFO,
    assessments: processedAssessments
  };
};

// ============ SITE ASSESSMENT REPORTS ============

// @desc    Get Site Assessment Report
// @route   GET /api/admin/reports/site-assessment
// @access  Private (Admin)
exports.getSiteAssessmentReport = async (req, res) => {
  try {
    console.log('[SiteAssessment] Fetching report with params:', req.query);
    const reportData = await getSiteAssessmentData(req.query);
    return res.json({ success: true, report: reportData });
  } catch (error) {
    console.error('[SiteAssessment] Error:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to generate site assessment report',
      error: error.message
    });
  }
};

// @desc    Export Site Assessment Report
// @route   POST /api/admin/reports/export (with type: site-assessment)
// @access  Private (Admin)
exports.exportSiteAssessmentReport = async (req, res) => {
  try {
    const { format, data } = req.body;

    if (!format || !data) {
      return res.status(400).json({
        success: false,
        message: 'Missing required fields: format and data are required'
      });
    }

    if (format === 'csv') {
      let csvContent = '';
      csvContent += `${COMPANY_INFO.name}\n`;
      csvContent += `${COMPANY_INFO.address}\n`;
      csvContent += `${COMPANY_INFO.tagline}\n`;
      csvContent += `Report Generated: ${new Date().toLocaleString()}\n`;
      csvContent += `Report Type: Site Assessment Report\n`;
      csvContent += `Date Range: ${data.dateRange?.startDate || 'All'} to ${data.dateRange?.endDate || 'All'}\n`;
      csvContent += `\n`;

      // ✅ Only 5 columns
      const headers = [
        'Booking Reference', 'Client Name', 'Contact', 'Type', 'Status'
      ];
      csvContent += headers.join(',') + '\n';

      const rows = (data.assessments || []).map(a => [
        `"${(a.bookingReference || 'N/A').replace(/"/g, '""')}"`,
        `"${(a.clientName || 'N/A').replace(/"/g, '""')}"`,
        `"${(a.clientContact || 'N/A').replace(/"/g, '""')}"`,
        `"${(a.propertyType || 'N/A').replace(/"/g, '""')}"`,
        `"${(a.statusDisplay || 'N/A').replace(/"/g, '""')}"`
      ]);

      csvContent += rows.map(row => row.join(',')).join('\n');

      res.setHeader('Content-Type', 'text/csv; charset=utf-8');
      res.setHeader('Content-Disposition', `attachment; filename=site-assessment-report-${Date.now()}.csv`);
      return res.send(csvContent);
    }

    if (format === 'pdf') {
      if (!PDFDocument) {
        return res.status(501).json({ message: 'PDF export not available. Install pdfkit.' });
      }

      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename=site-assessment-report-${Date.now()}.pdf`);
      doc.pipe(res);

      addCompanyHeaderToPDF(doc);

      doc.fillColor(REPORT_THEME.navy).fontSize(20).font('Helvetica-Bold').text('Site Assessment Report', { align: 'center' });
      doc.moveDown(0.35);
      doc.fillColor(REPORT_THEME.muted).fontSize(9).font('Helvetica')
        .text(`Generated ${new Date().toLocaleString()}  •  ${data.assessments?.length || 0} record(s)`, { align: 'center' });
      doc.moveDown(1.2);
      doc.fillColor(REPORT_THEME.navy).fontSize(11).font('Helvetica-Bold').text('Assessment Details');
      doc.moveDown(0.4);

      // ✅ Only 5 columns
      if (data.assessments && data.assessments.length > 0) {
        const headers_pdf = ['Booking Ref', 'Client Name', 'Contact', 'Type', 'Status'];
        const rows = data.assessments.map(a => [a.bookingReference, a.clientName, a.clientContact, a.propertyType, a.statusDisplay]);
        drawPdfTable(doc, headers_pdf, rows, [92, 118, 100, 78, 112]);
      }

      addPdfFooter(doc);
      doc.end();
      return;
    }

    if (format === 'xlsx') {
      if (!ExcelJS) {
        return res.status(501).json({ message: 'Excel export not available. Install exceljs.' });
      }

      const workbook = new ExcelJS.Workbook();
      buildExcelReport({

        workbook,

        sheetName: "Site Assessment",

        reportTitle: "Site Assessment Report",

        sectionTitle: "Assessment Details",

        headers: [
          "Booking Ref",
          "Client Name",
          "Contact",
          "Type",
          "Status"
        ],

        rows: (data.assessments || []).map(a => [
          a.bookingReference,
          a.clientName,
          a.clientContact,
          a.propertyType,
          a.statusDisplay
        ])

      });

      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', `attachment; filename=site-assessment-report-${Date.now()}.xlsx`);
      await workbook.xlsx.write(res);
      res.end();
      return;
    }

    res.status(400).json({ message: `Invalid format '${format}'. Use csv, pdf, or xlsx` });

  } catch (error) {
    console.error('[Export SiteAssessment] Error:', error);
    res.status(500).json({ message: 'Failed to export report', error: error.message });
  }
};

// ============ PROJECT SUMMARY REPORTS ============

// Helper function to get project summary data - ONLY 6 columns
const getProjectSummaryData = async (queryParams) => {
  const { startDate, endDate, projectId } = queryParams;

  let query = {};
  if (projectId && projectId.match(/^[0-9a-fA-F]{24}$/)) {
    query._id = projectId;
  }

  if (startDate && endDate) {
    const start = new Date(startDate);
    const end = new Date(endDate);
    if (!isNaN(start.getTime()) && !isNaN(end.getTime())) {
      query.createdAt = { $gte: start, $lte: end };
    }
  }

  const projects = await Project.find(query)
    .populate('clientId', 'contactFirstName contactLastName contactNumber client_type')
    .sort({ createdAt: -1 });

  const processedProjects = projects.map(p => {
    let status = 'Pending';
    if (p.status === 'in_progress') status = 'In Progress';
    else if (p.status === 'completed') status = 'Completed';
    else if (p.status === 'full_paid') status = 'Full Payment';
    else if (p.status === 'initial_paid') status = 'Initial Paid';
    else if (p.status === 'quoted') status = 'Quoted';
    else if (p.status === 'approved') status = 'Approved';

    return {
      projectReference: p.projectReference || 'N/A',
      clientName: `${p.clientId?.contactFirstName || ''} ${p.clientId?.contactLastName || ''}`.trim() || 'N/A',
      clientContact: p.clientId?.contactNumber || 'N/A',
      systemType: p.systemType || 'N/A',
      systemSize: p.systemSize || 'N/A',
      status: status
    };
  });

  return {
    title: 'Project Summary Report',
    generatedAt: new Date(),
    dateRange: { startDate, endDate },
    companyInfo: COMPANY_INFO,
    projects: processedProjects
  };
};

// @desc    Get Project Summary Report
// @route   GET /api/admin/reports/project-summary
// @access  Private (Admin)
exports.getProjectSummaryReport = async (req, res) => {
  try {
    console.log('[ProjectSummary] Fetching report with params:', req.query);
    const reportData = await getProjectSummaryData(req.query);
    return res.json({ success: true, report: reportData });
  } catch (error) {
    console.error('[ProjectSummary] Error:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to generate project summary report',
      error: error.message
    });
  }
};

// @desc    Export Project Summary Report
// @route   POST /api/admin/reports/export (with type: project-summary)
// @access  Private (Admin)
exports.exportProjectSummaryReport = async (req, res) => {
  try {
    const { format, data } = req.body;

    if (!format || !data) {
      return res.status(400).json({
        success: false,
        message: 'Missing required fields: format and data are required'
      });
    }

    if (format === 'csv') {
      let csvContent = '';
      csvContent += `${COMPANY_INFO.name}\n`;
      csvContent += `${COMPANY_INFO.address}\n`;
      csvContent += `${COMPANY_INFO.tagline}\n`;
      csvContent += `Report Generated: ${new Date().toLocaleString()}\n`;
      csvContent += `Report Type: Project Summary Report\n`;
      csvContent += `Date Range: ${data.dateRange?.startDate || 'All'} to ${data.dateRange?.endDate || 'All'}\n`;
      csvContent += `\n`;

      // ✅ Only 6 columns
      const headers = [
        'Project Ref', 'Client Name', 'Contact', 'System Type', 'System Size', 'Status'
      ];
      csvContent += headers.join(',') + '\n';

      const rows = (data.projects || []).map(p => [
        `"${(p.projectReference || 'N/A').replace(/"/g, '""')}"`,
        `"${(p.clientName || 'N/A').replace(/"/g, '""')}"`,
        `"${(p.clientContact || 'N/A').replace(/"/g, '""')}"`,
        `"${(p.systemType || 'N/A').replace(/"/g, '""')}"`,
        `"${(p.systemSize || 'N/A').replace(/"/g, '""')}"`,
        `"${(p.status || 'N/A').replace(/"/g, '""')}"`
      ]);

      csvContent += rows.map(row => row.join(',')).join('\n');

      res.setHeader('Content-Type', 'text/csv; charset=utf-8');
      res.setHeader('Content-Disposition', `attachment; filename=project-summary-report-${Date.now()}.csv`);
      return res.send(csvContent);
    }

    if (format === 'pdf') {
      if (!PDFDocument) {
        return res.status(501).json({ message: 'PDF export not available. Install pdfkit.' });
      }

      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename=project-summary-report-${Date.now()}.pdf`);
      doc.pipe(res);

      addCompanyHeaderToPDF(doc);

      doc.fillColor(REPORT_THEME.navy).fontSize(20).font('Helvetica-Bold').text('Project Summary Report', { align: 'center' });
      doc.moveDown(0.35);
      doc.fillColor(REPORT_THEME.muted).fontSize(9).font('Helvetica')
        .text(`Generated ${new Date().toLocaleString()}  •  ${data.projects?.length || 0} record(s)`, { align: 'center' });
      doc.moveDown(1.2);
      doc.fillColor(REPORT_THEME.navy).fontSize(11).font('Helvetica-Bold').text('Project Details');
      doc.moveDown(0.4);

      // ✅ Only 6 columns
      if (data.projects && data.projects.length > 0) {
        const headers_pdf = ['Project Ref', 'Client Name', 'Contact', 'System Type', 'System Size', 'Status'];
        const rows = data.projects.map(p => [p.projectReference, p.clientName, p.clientContact, p.systemType, p.systemSize, p.status]);
        drawPdfTable(doc, headers_pdf, rows, [88, 112, 88, 78, 62, 72]);
      }

      addPdfFooter(doc);
      doc.end();
      return;
    }

    if (format === 'xlsx') {
      if (!ExcelJS) {
        return res.status(501).json({ message: 'Excel export not available. Install exceljs.' });
      }

      const workbook = new ExcelJS.Workbook();
      buildExcelReport({

        workbook,

        sheetName: "Project Summary",

        reportTitle: "Project Summary Report",

        sectionTitle: "Project Details",

        headers: [
          "Project Ref",
          "Client Name",
          "Contact",
          "System Type",
          "System Size",
          "Status"
        ],

        rows: (data.projects || []).map(p => [
          p.projectReference,
          p.clientName,
          p.clientContact,
          p.systemType,
          p.systemSize,
          p.status
        ])

      });
      styleWorksheetTable(worksheet, dataRow.number);

      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', `attachment; filename=project-summary-report-${Date.now()}.xlsx`);
      await workbook.xlsx.write(res);
      res.end();
      return;
    }

    res.status(400).json({ message: `Invalid format '${format}'. Use csv, pdf, or xlsx` });

  } catch (error) {
    console.error('[Export ProjectSummary] Error:', error);
    res.status(500).json({ message: 'Failed to export report', error: error.message });
  }
};

// ============ FINANCIAL REPORTS ============

// Helper function to get financial data - ONLY 6 columns
const getFinancialData = async (queryParams) => {
  const { startDate, endDate } = queryParams;

  let dateFilter = {};
  if (startDate && endDate) {
    const start = new Date(startDate);
    const end = new Date(endDate);
    if (!isNaN(start.getTime()) && !isNaN(end.getTime())) {
      dateFilter = { createdAt: { $gte: start, $lte: end } };
    }
  }

  // Get pre-assessments with payments
  const preAssessments = await PreAssessment.find({
    ...dateFilter,
    paymentStatus: { $in: ['paid', 'for_verification'] }
  }).populate('clientId', 'contactFirstName contactLastName');

  // Get projects with payments
  const projects = await Project.find({
    ...dateFilter,
    amountPaid: { $gt: 0 }
  }).populate('clientId', 'contactFirstName contactLastName');

  const payments = [];

  // Pre-assessment payments
  preAssessments.forEach(pa => {
    payments.push({
      reference: pa.bookingReference || 'N/A',
      clientName: `${pa.clientId?.contactFirstName || ''} ${pa.clientId?.contactLastName || ''}`.trim() || 'N/A',
      amount: pa.assessmentFee || 0,
      paymentMethod: pa.paymentGateway === 'paymongo' ? 'PayMongo' : (pa.paymentMethod || 'Manual').toUpperCase(),
      status: pa.paymentStatus === 'paid' ? 'Paid' : 'For Verification',
      date: pa.paymentCompletedAt || pa.confirmedAt || pa.createdAt
    });
  });

  // Project payments
  projects.forEach(p => {
    let status = 'In Progress';
    if (p.status === 'completed') status = 'Completed';
    else if (p.status === 'full_paid') status = 'Full Payment Received';

    payments.push({
      reference: p.projectReference || 'N/A',
      clientName: `${p.clientId?.contactFirstName || ''} ${p.clientId?.contactLastName || ''}`.trim() || 'N/A',
      amount: p.amountPaid || 0,
      paymentMethod: 'Manual',
      status: status,
      date: p.startDate || p.createdAt
    });
  });

  payments.sort((a, b) => new Date(b.date) - new Date(a.date));

  return {
    title: 'Financial Report',
    generatedAt: new Date(),
    dateRange: { startDate, endDate },
    companyInfo: COMPANY_INFO,
    payments: payments
  };
};

// @desc    Get Financial Report
// @route   GET /api/admin/reports/financial
// @access  Private (Admin)
exports.getFinancialReport = async (req, res) => {
  try {
    console.log('[Financial] Fetching report with params:', req.query);
    const reportData = await getFinancialData(req.query);
    return res.json({ success: true, report: reportData });
  } catch (error) {
    console.error('[Financial] Error:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to generate financial report',
      error: error.message
    });
  }
};

// @desc    Export Financial Report
// @route   POST /api/admin/reports/export (with type: financial)
// @access  Private (Admin)
exports.exportFinancialReport = async (req, res) => {
  try {
    const { format, data } = req.body;

    if (!format || !data) {
      return res.status(400).json({
        success: false,
        message: 'Missing required fields: format and data are required'
      });
    }

    if (format === 'csv') {
      let csvContent = '';
      csvContent += `${COMPANY_INFO.name}\n`;
      csvContent += `${COMPANY_INFO.address}\n`;
      csvContent += `${COMPANY_INFO.tagline}\n`;
      csvContent += `Report Generated: ${new Date().toLocaleString()}\n`;
      csvContent += `Report Type: Financial Report\n`;
      csvContent += `Date Range: ${data.dateRange?.startDate || 'All'} to ${data.dateRange?.endDate || 'All'}\n`;
      csvContent += `\n`;

      // ✅ Only 6 columns
      const headers = [
        'Project/Booking Ref', 'Client Name', 'Amount', 'Payment Method', 'Status', 'Date'
      ];
      csvContent += headers.join(',') + '\n';

      const rows = (data.payments || []).map(p => [
        `"${(p.reference || 'N/A').replace(/"/g, '""')}"`,
        `"${(p.clientName || 'N/A').replace(/"/g, '""')}"`,
        p.amount || 0,
        `"${(p.paymentMethod || 'N/A').replace(/"/g, '""')}"`,
        `"${(p.status || 'N/A').replace(/"/g, '""')}"`,
        p.date ? new Date(p.date).toLocaleDateString() : 'N/A'
      ]);

      csvContent += rows.map(row => row.join(',')).join('\n');

      res.setHeader('Content-Type', 'text/csv; charset=utf-8');
      res.setHeader('Content-Disposition', `attachment; filename=financial-report-${Date.now()}.csv`);
      return res.send(csvContent);
    }

    if (format === 'pdf') {
      if (!PDFDocument) {
        return res.status(501).json({ message: 'PDF export not available. Install pdfkit.' });
      }

      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename=financial-report-${Date.now()}.pdf`);
      doc.pipe(res);

      addCompanyHeaderToPDF(doc);

      doc.fillColor(REPORT_THEME.navy).fontSize(20).font('Helvetica-Bold').text('Financial Report', { align: 'center' });
      doc.moveDown(0.35);
      doc.fillColor(REPORT_THEME.muted).fontSize(9).font('Helvetica')
        .text(`Generated ${new Date().toLocaleString()}  •  ${data.payments?.length || 0} record(s)`, { align: 'center' });
      doc.moveDown(1.2);
      doc.fillColor(REPORT_THEME.navy).fontSize(11).font('Helvetica-Bold').text('Payment Details');
      doc.moveDown(0.4);

      // ✅ Only 6 columns
      if (data.payments && data.payments.length > 0) {
        const headers_pdf = ['Reference', 'Client Name', 'Amount', 'Payment Method', 'Status', 'Date'];
        const rows = data.payments.map(p => [p.reference, p.clientName, p.amount ? `PHP ${Number(p.amount).toFixed(2)}` : 'N/A', p.paymentMethod, p.status, p.date ? new Date(p.date).toLocaleDateString() : 'N/A']);
        drawPdfTable(doc, headers_pdf, rows, [82, 110, 74, 88, 74, 72]);
      }

      if (false && data.payments && data.payments.length > 0) {
        doc.fontSize(12).font('Helvetica-Bold').text('Payment Details', { underline: true });
        doc.moveDown(0.5);

        const headers_pdf = ['Reference', 'Client Name', 'Amount', 'Payment Method', 'Status', 'Date'];
        const colWidths = [70, 90, 60, 60, 60, 70];
        let x = 50;
        let y = doc.y;

        doc.fontSize(8).font('Helvetica-Bold');
        headers_pdf.forEach((col, i) => {
          doc.text(col, x, y, { width: colWidths[i] });
          x += colWidths[i];
        });
        y += 15;

        doc.fontSize(7).font('Helvetica');
        (data.payments || []).forEach(p => {
          if (y > 750) {
            doc.addPage();
            y = 50;
            x = 50;
            doc.fontSize(8).font('Helvetica-Bold');
            headers_pdf.forEach((col, i) => {
              doc.text(col, x, y, { width: colWidths[i] });
              x += colWidths[i];
            });
            y += 15;
            doc.fontSize(7).font('Helvetica');
          }
          x = 50;
          doc.text((p.reference || 'N/A').substring(0, 15), x, y, { width: colWidths[0] });
          x += colWidths[0];
          doc.text((p.clientName || 'N/A').substring(0, 20), x, y, { width: colWidths[1] });
          x += colWidths[1];
          doc.text(p.amount ? `₱${p.amount.toFixed(2)}` : 'N/A', x, y, { width: colWidths[2] });
          x += colWidths[2];
          doc.text((p.paymentMethod || 'N/A').substring(0, 15), x, y, { width: colWidths[3] });
          x += colWidths[3];
          doc.text((p.status || 'N/A').substring(0, 20), x, y, { width: colWidths[4] });
          x += colWidths[4];
          doc.text(p.date ? new Date(p.date).toLocaleDateString() : 'N/A', x, y, { width: colWidths[5] });
          y += 12;
        });
      }

      addPdfFooter(doc);
      doc.end();
      return;
    }

    if (format === 'xlsx') {
      if (!ExcelJS) {
        return res.status(501).json({ message: 'Excel export not available. Install exceljs.' });
      }

      const workbook = new ExcelJS.Workbook();
      buildExcelReport({

        workbook,

        sheetName: "Financial",

        reportTitle: "Financial Report",

        sectionTitle: "Payment Details",

        headers: [
          "Reference",
          "Client Name",
          "Amount",
          "Method",
          "Status",
          "Date"
        ],

        rows: (data.payments || []).map(p => [
          p.reference,
          p.clientName,
          formatCurrency(p.amount),
          p.paymentMethod,
          p.status,
          p.date
            ? new Date(p.date).toLocaleDateString()
            : "N/A"
        ])

      });

      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', `attachment; filename=financial-report-${Date.now()}.xlsx`);
      await workbook.xlsx.write(res);
      res.end();
      return;
    }

    res.status(400).json({ message: `Invalid format '${format}'. Use csv, pdf, or xlsx` });

  } catch (error) {
    console.error('[Export Financial] Error:', error);
    res.status(500).json({ message: 'Failed to export report', error: error.message });
  }
};
// ============ CLIENT TRANSACTION REPORTS ============

// Helper function to get client data - ONLY 5 columns
const getClientTransactionData = async (queryParams) => {
  const { startDate, endDate, clientId } = queryParams;

  let clientFilter = {};
  if (clientId && clientId.match(/^[0-9a-fA-F]{24}$/)) {
    clientFilter._id = clientId;
  }

  let dateFilter = {};
  if (startDate && endDate) {
    const start = new Date(startDate);
    const end = new Date(endDate);
    if (!isNaN(start.getTime()) && !isNaN(end.getTime())) {
      dateFilter = { createdAt: { $gte: start, $lte: end } };
    }
  }

  const clients = await Client.find({
    ...clientFilter,
    ...dateFilter
  }).populate('userId', 'email').lean();

  // Get addresses for clients
  const clientIds = clients.map(c => c._id);
  const addresses = await Address.find({
    clientId: { $in: clientIds },
    isPrimary: true
  }).lean();

  const addressMap = {};
  addresses.forEach(addr => {
    if (addr.clientId) {
      addressMap[addr.clientId.toString()] = addr;
    }
  });

  const processedClients = clients.map(client => {
    const address = addressMap[client._id.toString()];
    let addressStr = 'N/A';
    if (address) {
      const parts = [
        address.houseOrBuilding,
        address.street,
        address.barangay,
        address.cityMunicipality
      ].filter(p => p && p.trim());
      addressStr = parts.join(', ') || 'N/A';
    }

    return {
      clientName: `${client.contactFirstName || ''} ${client.contactLastName || ''}`.trim() || 'N/A',
      clientContact: client.contactNumber || 'N/A',
      email: client.userId?.email || 'N/A',
      clientType: client.client_type || 'Residential',
      address: addressStr
    };
  });

  return {
    title: 'Clients Report',
    generatedAt: new Date(),
    dateRange: { startDate, endDate },
    companyInfo: COMPANY_INFO,
    clients: processedClients
  };
};

// @desc    Get Client Transaction Report
// @route   GET /api/admin/reports/client-transaction
// @access  Private (Admin)
exports.getClientTransactionReport = async (req, res) => {
  try {
    console.log('[ClientTransaction] Fetching report with params:', req.query);
    const reportData = await getClientTransactionData(req.query);
    return res.json({ success: true, report: reportData });
  } catch (error) {
    console.error('[ClientTransaction] Error:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to generate client transaction report',
      error: error.message
    });
  }
};

// @desc    Export Client Transaction Report
// @route   POST /api/admin/reports/export (with type: client-transaction)
// @access  Private (Admin)
exports.exportClientTransactionReport = async (req, res) => {
  try {
    const { format, data } = req.body;

    if (!format || !data) {
      return res.status(400).json({
        success: false,
        message: 'Missing required fields: format and data are required'
      });
    }

    // Handle both data formats
    let clients = [];
    if (Array.isArray(data)) {
      clients = data;
    } else if (data.clients) {
      clients = data.clients;
    } else {
      return res.status(400).json({
        success: false,
        message: 'Invalid data format. Expected array of clients or object with clients property.'
      });
    }

    if (format === 'csv') {
      let csvContent = '';
      csvContent += `${COMPANY_INFO.name}\n`;
      csvContent += `${COMPANY_INFO.address}\n`;
      csvContent += `${COMPANY_INFO.tagline}\n`;
      csvContent += `Report Generated: ${new Date().toLocaleString()}\n`;
      csvContent += `Report Type: Clients Report\n`;
      csvContent += `Date Range: ${data.dateRange?.startDate || 'All'} to ${data.dateRange?.endDate || 'All'}\n`;
      csvContent += `\n`;

      // ✅ Only 5 columns
      const headers = ['Name', 'Contact', 'Email', 'Client Type', 'Address'];
      csvContent += headers.join(',') + '\n';

      const rows = clients.map(c => [
        `"${(c.clientName || 'N/A').replace(/"/g, '""')}"`,
        `"${(c.clientContact || 'N/A').replace(/"/g, '""')}"`,
        `"${(c.email || 'N/A').replace(/"/g, '""')}"`,
        `"${(c.clientType || 'Residential').replace(/"/g, '""')}"`,
        `"${(c.address || 'N/A').replace(/"/g, '""')}"`
      ]);

      csvContent += rows.map(row => row.join(',')).join('\n');

      res.setHeader('Content-Type', 'text/csv; charset=utf-8');
      res.setHeader('Content-Disposition', `attachment; filename=clients-report-${Date.now()}.csv`);
      return res.send(csvContent);
    }

    if (format === 'pdf') {
      if (!PDFDocument) {
        return res.status(501).json({ message: 'PDF export not available. Install pdfkit.' });
      }

      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename=clients-report-${Date.now()}.pdf`);
      doc.pipe(res);

      addCompanyHeaderToPDF(doc);

      doc.fillColor(REPORT_THEME.navy).fontSize(20).font('Helvetica-Bold').text('Clients Report', { align: 'center' });
      doc.moveDown(0.35);
      doc.fillColor(REPORT_THEME.muted).fontSize(9).font('Helvetica')
        .text(`Generated ${new Date().toLocaleString()}  •  ${clients.length || 0} record(s)`, { align: 'center' });
      doc.moveDown(1.2);
      doc.fillColor(REPORT_THEME.navy).fontSize(11).font('Helvetica-Bold').text('Client Details');
      doc.moveDown(0.4);

      // ✅ Only 5 columns
      if (clients && clients.length > 0) {
        const headers_pdf = ['Name', 'Contact', 'Email', 'Client Type', 'Address'];
        const rows = clients.map(c => [c.clientName, c.clientContact, c.email, c.clientType || 'Residential', c.address]);
        drawPdfTable(doc, headers_pdf, rows, [105, 88, 132, 85, 90]);
      }

      if (false && clients && clients.length > 0) {
        doc.fontSize(12).font('Helvetica-Bold').text('Client Details', { underline: true });
        doc.moveDown(0.5);

        const headers_pdf = ['Name', 'Contact', 'Email', 'Client Type', 'Address'];
        const colWidths = [80, 70, 90, 60, 100];
        let x = 50;
        let y = doc.y;

        doc.fontSize(8).font('Helvetica-Bold');
        headers_pdf.forEach((col, i) => {
          doc.text(col, x, y, { width: colWidths[i] });
          x += colWidths[i];
        });
        y += 15;

        doc.fontSize(7).font('Helvetica');
        clients.forEach(c => {
          if (y > 750) {
            doc.addPage();
            y = 50;
            x = 50;
            doc.fontSize(8).font('Helvetica-Bold');
            headers_pdf.forEach((col, i) => {
              doc.text(col, x, y, { width: colWidths[i] });
              x += colWidths[i];
            });
            y += 15;
            doc.fontSize(7).font('Helvetica');
          }
          x = 50;
          doc.text((c.clientName || 'N/A').substring(0, 20), x, y, { width: colWidths[0] });
          x += colWidths[0];
          doc.text((c.clientContact || 'N/A').substring(0, 15), x, y, { width: colWidths[1] });
          x += colWidths[1];
          doc.text((c.email || 'N/A').substring(0, 25), x, y, { width: colWidths[2] });
          x += colWidths[2];
          doc.text((c.clientType || 'Residential').substring(0, 15), x, y, { width: colWidths[3] });
          x += colWidths[3];
          doc.text((c.address || 'N/A').substring(0, 25), x, y, { width: colWidths[4] });
          y += 12;
        });
      }

      addPdfFooter(doc);
      doc.end();
      return;
    }

    if (format === 'xlsx') {
      if (!ExcelJS) {
        return res.status(501).json({ message: 'Excel export not available. Install exceljs.' });
      }

      const workbook = new ExcelJS.Workbook();
      buildExcelReport({

        workbook,

        sheetName: "Clients",

        reportTitle: "Clients Report",

        sectionTitle: "Client Details",

        headers: [
          "Name",
          "Contact",
          "Email",
          "Type",
          "Address"
        ],

        rows: clients.map(c => [
          c.clientName,
          c.clientContact,
          c.email,
          c.clientType,
          c.address
        ])

      });

      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', `attachment; filename=clients-report-${Date.now()}.xlsx`);
      await workbook.xlsx.write(res);
      res.end();
      return;
    }

    res.status(400).json({ message: `Invalid format '${format}'. Use csv, pdf, or xlsx` });

  } catch (error) {
    console.error('[Export ClientTransaction] Error:', error);
    res.status(500).json({ message: 'Failed to export report', error: error.message });
  }
};

// ============ HELPER FUNCTIONS FOR ADMIN ============

// controllers/reportController.js

// @desc    Get all clients for dropdown
// @route   GET /api/admin/clients
// @access  Private (Admin)
exports.getAllClients = async (req, res) => {
  try {
    console.log('[GetClients] Fetching all clients');

    // Get all clients
    const clients = await Client.find()
      .select('contactFirstName contactLastName contactNumber client_type userId')
      .lean();

    console.log(`[GetClients] Found ${clients.length} clients`);

    // Get ALL users with email
    const users = await User.find()
      .select('_id email fullName')
      .lean();

    // Create email lookup map
    const userMap = {};
    users.forEach(user => {
      if (user._id) {
        userMap[user._id.toString()] = {
          email: user.email,
          fullName: user.fullName
        };
      }
    });
    console.log(`[GetClients] Found ${users.length} users for lookup`);

    // Get all addresses for clients
    const clientIds = clients.map(c => c._id);
    const addresses = await Address.find({
      clientId: { $in: clientIds },
      isPrimary: true
    }).lean();

    // Create address map
    const addressMap = {};
    addresses.forEach(addr => {
      if (addr.clientId) {
        addressMap[addr.clientId.toString()] = addr;
      }
    });
    console.log(`[GetClients] Found ${addresses.length} primary addresses`);

    // Attach email and address to each client
    const clientsWithDetails = clients.map(client => {
      const clientObj = { ...client };

      // Look up email from userMap
      if (client.userId) {
        const userIdStr = client.userId.toString();
        const userData = userMap[userIdStr];
        if (userData) {
          clientObj.email = userData.email || null;
          clientObj.fullName = userData.fullName || null;
        } else {
          clientObj.email = null;
          clientObj.fullName = null;
        }
      } else {
        clientObj.email = null;
        clientObj.fullName = null;
      }

      // Attach primary address if exists
      const address = addressMap[client._id.toString()];
      if (address) {
        clientObj.address = address;
      } else {
        clientObj.address = null;
      }

      // Remove userId if not needed in response
      delete clientObj.userId;

      return clientObj;
    });

    console.log(`[GetClients] Returning ${clientsWithDetails.length} clients with details`);

    res.json({ success: true, clients: clientsWithDetails });

  } catch (error) {
    console.error('[GetClients] Error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch clients',
      error: error.message
    });
  }
};

// @desc    Get client stats
// @route   GET /api/admin/clients/stats
// @access  Private (Admin)
exports.getClientStats = async (req, res) => {
  try {
    console.log('[GetClientStats] Fetching client statistics');

    const total = await Client.countDocuments();
    const residential = await Client.countDocuments({ client_type: 'Residential' });
    const company = await Client.countDocuments({ client_type: 'Company' });
    const industrial = await Client.countDocuments({ client_type: 'Industrial' });

    const currentMonth = new Date();
    currentMonth.setDate(1);
    currentMonth.setHours(0, 0, 0, 0);

    const newThisMonth = await Client.countDocuments({
      createdAt: { $gte: currentMonth }
    });

    console.log(`[GetClientStats] Total: ${total}, New this month: ${newThisMonth}`);

    res.json({
      success: true,
      stats: { total, residential, company, industrial, active: total, new: newThisMonth }
    });
  } catch (error) {
    console.error('[GetClientStats] Error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch client stats',
      error: error.message
    });
  }
};

// @desc    Generate custom report
// @route   POST /api/admin/reports/generate
// @access  Private (Admin)
exports.generateCustomReport = async (req, res) => {
  try {
    console.log('[GenerateCustom] Request body:', req.body);

    const { type, dateRange, filters } = req.body;

    if (!type) {
      return res.status(400).json({
        success: false,
        message: 'Missing required field: type. Options: site-assessment, project-summary, financial, client-transaction'
      });
    }

    let reportData = {};

    if (type === 'site-assessment') {
      reportData = await getSiteAssessmentData({
        startDate: dateRange?.startDate,
        endDate: dateRange?.endDate,
        assessmentId: filters?.assessmentId
      });
    } else if (type === 'project-summary') {
      reportData = await getProjectSummaryData({
        startDate: dateRange?.startDate,
        endDate: dateRange?.endDate,
        projectId: filters?.projectId
      });
    } else if (type === 'financial') {
      reportData = await getFinancialData({
        startDate: dateRange?.startDate,
        endDate: dateRange?.endDate
      });
    } else if (type === 'client-transaction') {
      reportData = await getClientTransactionData({
        startDate: dateRange?.startDate,
        endDate: dateRange?.endDate,
        clientId: filters?.clientId
      });
    } else {
      return res.status(400).json({
        success: false,
        message: `Invalid report type '${type}'. Options: site-assessment, project-summary, financial, client-transaction`
      });
    }

    res.json({ success: true, report: reportData });

  } catch (error) {
    console.error('[GenerateCustom] Error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to generate custom report',
      error: error.message
    });
  }
};

// @desc    Export report
// @route   POST /api/admin/reports/export
// @access  Private (Admin)
exports.exportReport = async (req, res) => {
  try {
    console.log('[Export] Request body:', req.body);

    const { format, type, data } = req.body;

    if (!format) {
      return res.status(400).json({
        success: false,
        message: 'Missing required field: format. Options: csv, pdf, xlsx'
      });
    }

    if (!type) {
      return res.status(400).json({
        success: false,
        message: 'Missing required field: type. Options: site-assessment, project-summary, financial, client-transaction'
      });
    }

    if (!data) {
      return res.status(400).json({
        success: false,
        message: 'Missing required field: data. Report data is required for export.'
      });
    }

    if (type === 'site-assessment') {
      return exports.exportSiteAssessmentReport(req, res);
    } else if (type === 'project-summary') {
      return exports.exportProjectSummaryReport(req, res);
    } else if (type === 'financial') {
      return exports.exportFinancialReport(req, res);
    } else if (type === 'client-transaction') {
      return exports.exportClientTransactionReport(req, res);
    }

    return res.status(400).json({
      success: false,
      message: `Invalid report type '${type}'. Options: site-assessment, project-summary, financial, client-transaction`
    });

  } catch (error) {
    console.error('[Export] Error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to export report',
      error: error.message
    });
  }
};
